CHAPTER_THEMES = {
    1: 'Arjuna ka sankat, manovaigyanik vishad aur yuddh ke prarambh ka varnan.',
    2: 'Atma ki avadharana, karm aur sanyas ka gyaan; jeevan mein sthirata ka marg.',
    3: 'Karma ki mahanta aur phal se anasaakta rehkar kartavya ka palan.',
    4: 'Sanskriti aur gyaan ka mel; karm, jnana aur sanyas ki samajh.',
    5: 'Karma sanyas aur karma yoga mein farq; aadhyatmik mukti ka marg.',
    6: 'Dhyana yoga aur man ko niyantrit karne ke upay.',
    7: 'Param brahma, jagat aur Ishwar ki mahatvapoorn jaanch.',
    8: 'Akshar brahma aur mritu ke baad atma ka safar.',
    9: 'Gupt gyaan aur bhakti ke mahatva ki prashansa.',
    10: 'Bhagwan ki mahanata aur vibhutiyon ka varnan.',
    11: 'Vishvarupa darshan aur Ishwar ke roop ka darshan.',
    12: 'Bhakti ka marg aur bhakt ka svabhav.',
    13: 'Kshetra aur kshetrajna, sharir aur atma ki pehchaan.',
    14: 'Gunon ka vibhajan: sattva, rajas aur tamas.',
    15: 'Purushottama aur anadi vyavastha ka vivechan.',
    16: 'Daivi aur asuri sampatti ka tulanatmak varnan.',
    17: 'Shraddha ke teen star aur unke parinaam.',
    18: 'Moksha, sanyas aur karma ke antim siddhant.',
}

GITA_TOPICS = [
    'Karma Yoga (Kriya ka marg)',
    'Bhakti Yoga (Shraddha aur prem)',
    'Jnana Yoga (Gyaan aur vivek)',
    'Dhyana Yoga (Man niyantran)',
    'Sankhya Yoga (Gyaan ka marg)',
    'Raja Yoga (Man niyantran)',
    'Hatha Yoga (Sharir aur pran)',
    'Kundalini Yoga (Urja jagran)',
    'Dharma aur kartavya',
    'Atma aur akhandatva',
    'Gunas: sattva, rajas, tamas',
    'Stitha prajna ka avastha',
    'Vishvarupa aur dyavy roop',
    'Mukti aur sanyas',
    'Arjuna ka sankat',
    'Krishna ka updesh',
    'Yuddh ka dharma',
    'Man ki shakti',
    'Buddhi aur vivek',
    'Tyag aur santushti',
    'Prem aur daya',
    'Kshama aur dhairya',
    'Safalta aur asafalta',
    'Lobh aur krodh',
    'Irsha aur garva',
    'Seva aur samarpan',
    'Gyaan aur ajnana',
    'Moksha ka marg',
    'Ishwar ki mahima',
    'Bhakt ka swabhav',
    'Karma ka fal',
    'Samsara ka chakra',
    'Atma ki amarata',
    'Sharir aur atma ka vibhajan',
    'Nishkaam karma',
    'Ishwararpan buddhi',
    'Trividha tapa',
    'Trividha yajna',
    'Trividha daan',
    'Daivi sampatti',
    'Asuri sampatti',
    'Shraddha ke teen bhed',
    'Purushottama tattva',
    'Ashvattha vriksha',
    'Kshetra kshetrajna vivek',
    'Guna aur karma',
    'Moksha sanyas yoga',
    'Bhagavad Gita ke char marg',
    'Arjuna ki jिज्ञासा',
    'Krishna ki divya shakti',
    'Yogeshwar Krishna',
    'Gupt gyaan',
    'Raj vidya raj guhya',
    'Akshar brahma',
    'Kshar brahma',
    'Mritu ka samay',
    'Om tat sat',
    'Sanyas aur tyag ka antar',
    'Karma phal tyag',
    'Ishwar ki vibhutiyan',
    'Bhakti ki mahima',
    'Dhyana ka updesh',
    'Man niyantran',
    'Atma samarpan',
    'Jeevan ka arth',
    'Mukti ki sadhana',
    'Adhyatma vidya',
    'Brahma vidya',
    'Yoga vidya',
    'Sankhya darshan',
    'Vedanta tattva',
    'Upanishad gyaan',
    'Smriti aur shruti',
    'Dharma shastra',
    'Karma kanda',
    'Jnana kanda',
    'Bhakti kanda',
    'Raja marg',
    'Hatha marg',
    'Laya marg',
    'Kundalini marg',
    'Sahaj marg',
    'Sant mat',
    'Sufi marg',
    'Vedantic path',
    'Tantric path',
    'Devotional path',
    'Intellectual path',
    'Action-oriented path',
    'Meditation path',
    'Service path',
    'Knowledge path',
    'Love path',
    'Wisdom path',
    'Duty path',
    'Renunciation path',
    'Liberation path',
]

GITA_ADVICE = {
    'fear': 'Arjuna bina soch ke khed aur bhay ki wajah se uljhan mein tha. Gita kehti hai: apne kartavya ko nishkaam roop se karo.',
    'career': 'Karma Yoga yaad rakho. Mehnat karo, par phal ka asakti chhodo.',
    'love': 'Prem aur tyag dono zaroori hain. Bhagavad Gita ka marg pyaar ko dhairy aur samarpan se jodta hai.',
    'stress': 'Dhyana aur ekagrata se man ko shaant karo. Gita ka sikhav hai: adhyatmik drishti se jeevan dekho.',
    'health': 'Gita mein sharir aur man ka santulan zaroori hai. niyamit karm aur dhyaan se swasthya banao.',
    'relationships': 'Rishton mein prem aur kartavya dono ka palan karo. Gita kahti hai: sabhi mein atma ko dekho.',
    'spirituality': 'Aadhyatmik marg mein gyaan aur bhakti dono zaroori hain. apne andar Ishwar ko khojo.',
    'success': 'Safalta mein vinamrata aur kartavya ka palan karo. Gita kahti hai: karm se safalta aati hai, par man ko niyantrit rakho.',
    'failure': 'Asafalta se mat ghabrao. Gita sikhaati hai: har asafalta se seekho aur fir se koshish karo.',
    'anger': 'Krodh ko niyantrit karo. Gita kehti hai: krodh se buddhi nasht ho jaati hai.',
    'greed': 'Lobh se bacho. Gita ka marg: santushti aur tyag se sukh milta hai.',
    'jealousy': 'Irsha ko door rakho. Gita sikhaati hai: sabhi mein samaanta dekho.',
    'forgiveness': 'Kshama ka gun sikho. Gita kehti hai: kshama se atma shuddh hoti hai.',
    'patience': 'Dhairya rakho. Gita ka sikhav: sabhi kaam mein dhairya aur vivek se kaam karo.',
    'leadership': 'Netritva mein dayalu bano. Gita kehti hai: neta ko apne anuyayi ka hit sochna chahiye.',
    'wealth': 'Dhan mein asakti mat karo. Gita sikhaati hai: dhan ka upyog samaj ke liye karo.',
    'education': 'Gyaan ki khoj karo. Gita kehti hai: gyaan hi mukt ka marg hai.',
    'family': 'Parivar mein kartavya nibhao. Gita ka marg: parivar aur samaj ka palan karo.',
    'friendship': 'Dosti mein sachai rakho. Gita sikhaati hai: sachche mitron se jeevan sudhar jata hai.',
    'loneliness': 'Akelaapan mein Ishwar ko yaad karo. Gita kehti hai: Ishwar sabhi ke saath hai.',
    'duty': 'Kartavya ko bina soch ke karo. Gita ka mool sikhav: dharma ka palan.',
    'detachment': 'Phal se anasaakta raho. Gita sikhaati hai: nishkaam karma se shanti.',
    'meditation': 'Dhyan se man ko shaant karo. Gita kehti hai: dhyana yoga se mukti.',
    'knowledge': 'Gyaan ko badhao. Gita ka marg: jnana yoga se atma jagruti.',
    'devotion': 'Bhakti se Ishwar ko prapt karo. Gita sikhaati hai: bhakti hi param sadhana.',
    'equanimity': 'Har haal mein samaanta rakho. Gita kehti hai: stitha prajna bano.',
    'sacrifice': 'Tyag karo. Gita ka sikhav: yajna aur daan se punya.',
    'self-control': 'Indriyon ko niyantrit karo. Gita sikhaati hai: man aur buddhi ko vash mein rakho.',
    'compassion': 'Daya ka bhav rakho. Gita kehti hai: sabhi jeevon mein daya.',
    'truth': 'Satya ka palan karo. Gita ka marg: sachai se jeevan sudhao.',
    'non-violence': 'Ahimsa ka gun sikho. Gita sikhaati hai: ahimsa se shanti.',
    'contentment': 'Santushti ka marg apnao. Gita kehti hai: santushti se anand.',
    'renunciation': 'Sanyas karo. Gita ka sikhav: sanyas se mukti.',
    'liberation': 'Moksha ki khoj karo. Gita sikhaati hai: moksha hi param lakshya.',
}

GITA_KEY_TEACHINGS = {
    1: [
        'Arjuna ka yuddh se inkaar aur uski uljhan.',
        'Krishna ka Arjuna ko yuddh ke liye prerit karna.',
        'Kauravon ki shakti ka varnan.',
        'Yuddh ka dharma aur kartavya.',
    ],
    2: [
        'Atma ki avinashi aur sharir ki nashtata.',
        'Karma yoga: nishkaam karma ka mahatva.',
        'Sthita prajna ka lakshan.',
        'Jnana, karma aur bhakti ka marg.',
    ],
    3: [
        'Karma ka mahatva aur usse bachna nahi.',
        'Nishkaam karma ka palan.',
        'Ishwar ki ichha se sab kuch hota hai.',
        'Gunas aur unka prabhav.',
    ],
    4: [
        'Gyaan ka punarjanam aur uska marg.',
        'Karma aur sanyas ka vibhajan.',
        'Bhakti ka mahatva.',
        'Ishwar ki mahima aur vibhutiyan.',
    ],
    5: [
        'Karma sanyas aur karma yoga ka antar.',
        'Mukti ka marg.',
        'Dhyana aur ekagrata.',
        'Atma ki shanti.',
    ],
    6: [
        'Dhyana yoga ka updesh.',
        'Man ki niyantran ki vidhi.',
        'Yog ka fal.',
        'Ishwar ka smaran.',
    ],
    7: [
        'Gyaan aur vijnana ka vibhajan.',
        'Ishwar ki prakriti aur jiva.',
        'Bhakti ka marg.',
        'Mukti ki sahajta.',
    ],
    8: [
        'Akshar brahma ka gyaan.',
        'Mritu ke samay ka mahatva.',
        'Yog aur sanyas.',
        'Ishwar ki smriti.',
    ],
    9: [
        'Gupt gyaan aur raj vidya.',
        'Bhakti ka mahatva.',
        'Ishwar ki sarvavyapi.',
        'Mukti ka marg.',
    ],
    10: [
        'Ishwar ki vibhutiyan.',
        'Bhakti se gyaan.',
        'Yogeshwar ka varnan.',
        'Ishwar ki mahima.',
    ],
    11: [
        'Vishvarupa darshan.',
        'Ishwar ki shakti.',
        'Arjuna ka bhay aur prarthana.',
        'Bhakti ka param lakshya.',
    ],
    12: [
        'Bhakti ka mahatva.',
        'Bhakt ka swabhav.',
        'Ishwar ki prapti.',
        'Tyag aur bhakti.',
    ],
    13: [
        'Kshetra aur kshetrajna.',
        'Gyaan ka marg.',
        'Purush aur prakriti.',
        'Mukti ka upay.',
    ],
    14: [
        'Guna ka vibhajan.',
        'Sattva, rajas, tamas ka prabhav.',
        'Guna se mukti.',
        'Ishwar ki bhakti.',
    ],
    15: [
        'Purushottama yoga.',
        'Ashvattha vriksha.',
        'Atma ki amarata.',
        'Bhakti ka fal.',
    ],
    16: [
        'Daivi aur asuri sampatti.',
        'Asuri swabhav se bacho.',
        'Dharma ka palan.',
        'Ishwar ki sharan.',
    ],
    17: [
        'Shraddha ka vibhajan.',
        'Tapas aur yajna.',
        'Daan ka mahatva.',
        'Om tat sat.',
    ],
    18: [
        'Sanyas aur tyag.',
        'Karma ka fal.',
        'Ishwararpan.',
        'Mukti ka ant.',
    ],
}

GITA_TOPICS = [
    'Karma Yoga (Kriya ka marg)',
    'Bhakti Yoga (Shraddha aur prem)',
    'Jnana Yoga (Gyaan aur vivek)',
    'Dhyana Yoga (Man niyantran)',
    'Sankhya Yoga (Gyaan ka marg)',
    'Raja Yoga (Man niyantran)',
    'Hatha Yoga (Sharir aur pran)',
    'Kundalini Yoga (Urja jagran)',
    'Dharma aur kartavya',
    'Atma aur akhandatva',
    'Gunas: sattva, rajas, tamas',
    'Stitha prajna ka avastha',
    'Vishvarupa aur dyavy roop',
    'Mukti aur sanyas',
    'Arjuna ka sankat',
    'Krishna ka updesh',
    'Yuddh ka dharma',
    'Man ki shakti',
    'Buddhi aur vivek',
    'Tyag aur santushti',
    'Prem aur daya',
    'Kshama aur dhairya',
    'Safalta aur asafalta',
    'Lobh aur krodh',
    'Irsha aur garva',
    'Seva aur samarpan',
    'Gyaan aur ajnana',
    'Moksha ka marg',
    'Ishwar ki mahima',
    'Bhakt ka swabhav',
    'Karma ka fal',
    'Samsara ka chakra',
    'Atma ki amarata',
    'Sharir aur atma ka vibhajan',
    'Nishkaam karma',
    'Ishwararpan buddhi',
    'Trividha tapa',
    'Trividha yajna',
    'Trividha daan',
    'Daivi sampatti',
    'Asuri sampatti',
    'Shraddha ke teen bhed',
    'Purushottama tattva',
    'Ashvattha vriksha',
    'Kshetra kshetrajna vivek',
    'Guna aur karma',
    'Moksha sanyas yoga',
    'Bhagavad Gita ke char marg',
    'Arjuna ki jिज्ञासा',
    'Krishna ki divya shakti',
    'Yogeshwar Krishna',
    'Gupt gyaan',
    'Raj vidya raj guhya',
    'Akshar brahma',
    'Kshar brahma',
    'Mritu ka samay',
    'Om tat sat',
    'Sanyas aur tyag ka antar',
    'Karma phal tyag',
    'Ishwar ki vibhutiyan',
    'Bhakti ki mahima',
    'Dhyana ka updesh',
    'Man niyantran',
    'Atma samarpan',
    'Jeevan ka arth',
    'Mukti ki sadhana',
    'Adhyatma vidya',
    'Brahma vidya',
    'Yoga vidya',
    'Sankhya darshan',
    'Vedanta tattva',
    'Upanishad gyaan',
    'Smriti aur shruti',
    'Dharma shastra',
    'Karma kanda',
    'Jnana kanda',
    'Bhakti kanda',
    'Raja marg',
    'Hatha marg',
    'Laya marg',
    'Kundalini marg',
    'Sahaj marg',
    'Sant mat',
    'Sufi marg',
    'Vedantic path',
    'Tantric path',
    'Devotional path',
    'Intellectual path',
    'Action-oriented path',
    'Meditation path',
    'Service path',
    'Knowledge path',
    'Love path',
    'Wisdom path',
    'Duty path',
    'Renunciation path',
    'Liberation path',
]

GITA_QUOTE_PROMPTS = [
    'Apna karya karo, phal ki chinta chhodo.',
    'Sthitaprajna vah hai jo har paristhiti mein shaant rahe.',
    'Gyaan hi tumhe mukt kar sakta hai, par uska prayog karna avashyak hai.',
    'Jeevan mein karya aur sanyas ka santulan jaruri hai.',
    'Atma hi sabhi mein samaan hai.',
    'Karma hi jeevan ka aadhar hai.',
    'Bhakti se sab kuch paaya ja sakta hai.',
    'Dhyan se man ko niyantrit karo.',
    'Ishwar sabhi ke andar basa hai.',
    'Kartavya ko bina soch ke karo.',
    'Prem hi sabse bada shakti hai.',
    'Gyaan bina karm ke adhura hai.',
    'Man ko ekagrata se kaam karo.',
    'Tyag se sukh milta hai.',
    'Dhairya se sab kuch jeeta ja sakta hai.',
    'Lobh se bacho, santushti ka marg apnao.',
    'Krodh ko niyantrit karo.',
    'Irsha ko door rakho.',
    'Kshama ka gun sikho.',
    'Seva se atma shuddh hoti hai.',
    'Safalta mein vinamrata rakho.',
    'Asafalta se mat ghabrao.',
    'Gyaan ka deep jalaao.',
    'Bhakti ka marg sabse saral hai.',
    'Moksha hi jeevan ka lakshya hai.',
    'Atma amar hai.',
    'Sharir nasht hone wala hai.',
    'Ishwar ki ichha se sab kuch hota hai.',
    'Karma ka fal anivarya hai.',
    'Samsara se mukti pao.',
    'Vivek se jeevan sudhao.',
    'Buddhi ko tez karo.',
    'Man ki shakti ko jagao.',
    'Dharma ka palan karo.',
    'Adharm se bacho.',
    'Sattva gun ko badhao.',
    'Rajas aur tamas ko kam karo.',
    'Stitha prajna bano.',
    'Vishvarupa ko dekho.',
    'Krishna ka updesh yaad rakho.',
    'Nishkaam karma karo.',
    'Ishwararpan buddhi rakho.',
    'Trividha tapa karo.',
    'Yajna ka palan karo.',
    'Daan se punya pao.',
    'Daivi sampatti ikatthi karo.',
    'Asuri sampatti tyago.',
    'Shraddha se kaam karo.',
    'Purushottama ko jano.',
    'Ashvattha ko kaato.',
    'Kshetra kshetrajna ko samjho.',
    'Guna se mukti pao.',
    'Moksha sanyas yoga karo.',
    'Char marg apnao.',
    'Jिज्ञासा rakho.',
    'Divya shakti ko dekho.',
    'Yogeshwar ko pranam karo.',
    'Gupt gyaan pao.',
    'Raj vidya sikho.',
    'Akshar brahma jano.',
    'Kshar brahma tyago.',
    'Mritu ka samay yaad rakho.',
    'Om tat sat bolo.',
    'Sanyas aur tyag ka antar jano.',
    'Karma phal tyag karo.',
    'Vibhutiyan dekho.',
    'Bhakti ki mahima jano.',
    'Dhyana ka updesh mano.',
    'Man niyantran karo.',
    'Atma samarpan karo.',
    'Jeevan ka arth samjho.',
    'Mukti ki sadhana karo.',
    'Adhyatma vidya sikho.',
    'Brahma vidya pao.',
    'Yoga vidya jano.',
    'Sankhya darshan padho.',
    'Vedanta tattva samjho.',
    'Upanishad gyaan pao.',
    'Smriti aur shruti mano.',
    'Dharma shastra padho.',
    'Karma kanda karo.',
    'Jnana kanda sikho.',
    'Bhakti kanda apnao.',
    'Raja marg chalo.',
    'Hatha marg karo.',
    'Laya marg jano.',
    'Kundalini marg chalo.',
    'Sahaj marg apnao.',
    'Sant mat sikho.',
    'Sufi marg chalo.',
    'Vedantic path apnao.',
    'Tantric path jano.',
    'Devotional path chalo.',
    'Intellectual path sikho.',
    'Action-oriented path karo.',
    'Meditation path apnao.',
    'Service path chalo.',
    'Knowledge path sikho.',
    'Love path apnao.',
    'Wisdom path chalo.',
    'Duty path karo.',
    'Renunciation path apnao.',
    'Liberation path chalo.',
]
